package com.linguan.codemd.stage01;

/** Stable M1 failure codes safe to surface without local filesystem details. */
public enum Stage01FailureCode {
    REQUEST_SCHEMA_INVALID,
    CAPTURE_IDENTITY_INVALID,
    PROFILE_REFERENCE_INVALID,
    SNAPSHOT_ROOT_INVALID,
    SOURCE_PATH_INVALID,
    SYMLINK_FORBIDDEN,
    DUPLICATE_SOURCE_PATH,
    SOURCE_NOT_REGULAR,
    SOURCE_SIZE_MISMATCH,
    SOURCE_HASH_MISMATCH,
    SOURCE_UTF8_INVALID,
    M1_RESOURCE_LIMIT_EXCEEDED,
    VERIFIED_SOURCE_REOPEN_MISMATCH,
    XML_SECURITY_POLICY_UNENFORCEABLE,
    XML_EXTERNAL_RESOLUTION_ATTEMPT,
    M2_GRAPH_INVARIANT_BROKEN,
    M3_ACCOUNTING_INVARIANT_BROKEN,
    PROOF_PACK_REFERENCE_BROKEN,
    PROOF_SOURCE_REOPEN_MISMATCH
}
