/**
 * Frozen, human-readable subset of the GitHub capture.
 *
 * This is deliberately a record projection, not a checkout.  It contains
 * locations and preserved extraction metadata from commit b3ab269…d7eb1;
 * where a source line was not retained, it never reconstructs source code or
 * SQL.  Regenerate only through the explicit evidence-maintenance workflow.
 */
export const generatedCuratedGithubReview = {
  schemaVersion: 1,
  sourceId: 'guanyijia_github',
  snapshotId: '20260813032126Z-5821d0ece9b1',
  title: 'GitHub 代码仓库审阅（冻结结构化记录）',
  coverageLabel: '14 条高信息密度冻结记录',
  markdown: [
    '# GitHub 代码仓库审阅（冻结结构化记录）',
    '',
    '> 本文档来自固定提交 `b3ab269…d7eb1` 的结构化归档。它保留文件、符号、表和行号；未保留完整源码的地方会明确说明，不能把记录当作完整源码原文。',
    '',
    '## 1. 文档说明',
    '<!-- github-g01 -->',
    '- 本次节选覆盖系统配置、单据字段演进、租户过滤、库存、批次序列号及统计 Mapper 记录。 [TRACE:G01]',
    '',
    '## 2. 业务目标',
    '<!-- github-g02 -->',
    '- `jsh_system_config` 的系统配置记录包含 `minus_stock_flag`；其名称和位置可供审阅负库存开关，具体执行逻辑仍需按后续证据核验。 [TRACE:G02]',
    '<!-- github-g03 -->',
    '- DepotHead 服务记录包含对负库存标记的读取步骤，说明该配置被工作流引用。 [TRACE:G03]',
    '',
    '## 3. 业务对象',
    '<!-- github-g04 -->',
    '- 冻结迁移记录显示 `jsh_depot_head` 曾调整状态字段的文字说明，只列出 0／1／2；状态 9 不在该历史记录中。它不代表当前部署状态。 [TRACE:G04]',
    '<!-- github-g05 -->',
    '- 冻结迁移记录列出 `debt` 与 `last_debt` 字段的演进；需与已部署 DDL 另行比较。 [TRACE:G05]',
    '<!-- github-g06 -->',
    '- TenantConfig 的过滤方法被归档为租户隔离规则记录。 [TRACE:G06]',
    '',
    '## 4. 业务活动',
    '<!-- github-g07 -->',
    '- 用户业务权限 Mapper 记录涉及基础数据授权查询；保存的是表、位置和结构化摘要。 [TRACE:G07]',
    '<!-- github-g08 -->',
    '- SerialNumberService 的查询方法被归档为序列号生命周期处理记录。 [TRACE:G08]',
    '<!-- github-g09 -->',
    '- DepotItemService 的批号查询方法被归档为库存明细检索记录。 [TRACE:G09]',
    '',
    '## 5. 字段与维度',
    '<!-- github-g10 -->',
    '- `jsh_material_current_stock` 被列入源码 schema 归档，表定义范围可在冻结记录中定位。 [TRACE:G10]',
    '<!-- github-g11 -->',
    '- `jsh_depot_item` 的结构化 schema 记录包含调拨相关字段范围；不在此重建 SQL 正文。 [TRACE:G11]',
    '',
    '## 6. 对象关系',
    '<!-- github-g12 -->',
    '- 销售／采购数量 Mapper statement 保存了涉及表、聚合和过滤信息，适合作为关系与指标候选，不是 SQL 原文。 [TRACE:G12]',
    '',
    '## 7. 指标口径',
    '<!-- github-g13 -->',
    '- 销售／采购金额 Mapper statement 保存了聚合型查询的结构化索引；完整指标公式仍待业务口径确认。 [TRACE:G13]',
    '',
    '## 8. 示例问题',
    '<!-- github-g14 -->',
    '- 可据冻结 Mapper 记录追问库存预警、销售采购汇总和账户收支的实现位置；缺少完整 SQL 时只能作为候选线索。 [TRACE:G14]',
    '',
    '## 9. 待确认事项',
    '- 归档未保留完整仓库 checkout、每个 Mapper 的 SQL 正文或全部服务方法体；这些内容保持“原文未保留”。',
    '- 与部署数据库的欠款字段、状态值和负库存治理关系，只有在本来源读入后才会在“本次读取发现”中比较。',
  ].join('\n'),
  evidence: [
    {
      evidenceRef: 'github:schema:system-config-minus-stock',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'EXACT_EXCERPT',
      title: '系统配置中的负库存开关字段',
      excerpt: "  `minus_stock_flag` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0' COMMENT '负库存启用标记，0未启用，1启用',",
      locationLabel: '冻结 schema 记录行',
      locationValue: 'schema/tables/jsh_system_config.sql:L12',
      affectedObjectRefs: ['table:jsh_system_config', 'field:minus_stock_flag'],
      artifactDigest: 'sha256:f4a8d4368b4c3ea322d52ad0baf1b002f4b93e69c71a431f41e4dd0fade5d12c',
    },
    {
      evidenceRef: 'github:service:minus-stock-flag',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '负库存标记读取方法',
      excerpt: '冻结服务记录：SystemConfigService.getMinusStockFlag；方法范围 L511–L521；关联配置字段 minus_stock_flag；完整方法体未保留。',
      locationLabel: '冻结服务方法记录',
      locationValue: 'jshERP-boot/src/main/java/com/jsh/erp/service/SystemConfigService.java:L511-L521',
      affectedObjectRefs: ['service:SystemConfigService.getMinusStockFlag', 'field:minus_stock_flag'],
      artifactDigest: 'sha256:4d1b24d4322e5af4516863ca8c519a6d9a245022a99a0095c5b776ac7b882a48',
    },
    {
      evidenceRef: 'github:service:depot-head-minus-stock',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '单据状态工作流中的负库存读取',
      excerpt: '冻结服务记录：DepotHeadService.batchSetStatus；方法范围 L742–L822；记录到读取 minusStockFlag 的工作流依赖；完整方法体未保留。',
      locationLabel: '冻结服务方法记录',
      locationValue: 'jshERP-boot/src/main/java/com/jsh/erp/service/DepotHeadService.java:L742-L822',
      affectedObjectRefs: ['service:DepotHeadService.batchSetStatus', 'table:jsh_depot_head'],
      artifactDigest: 'sha256:079e7ce20c3418013362a68e56451debc72e0fb97e5c43d60872dd4a9e94e5bd',
    },
    {
      evidenceRef: 'github:migration:jsh-depot-head-historical-status',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'EXACT_EXCERPT',
      title: '历史单据状态迁移记录',
      excerpt: "alter table jsh_depot_head change Status Status varchar(1) DEFAULT '0' COMMENT '状态，0未审核、1已审核、2已转采购|销售';",
      locationLabel: '冻结迁移记录行',
      locationValue: 'migration-history/数据库更新记录:L312',
      affectedObjectRefs: ['table:jsh_depot_head', 'field:status'],
      artifactDigest: 'sha256:d2e93166b0935166b86661061fa902324c0dbaa728b73eb26ddb677d022a4754',
    },
    {
      evidenceRef: 'github:migration:jsh-depot-head-debt-fields',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'EXACT_EXCERPT',
      title: '欠款字段迁移记录',
      excerpt: "alter table jsh_depot_head add debt decimal(24,6) DEFAULT NULL COMMENT '本次欠款' after deposit;\nalter table jsh_depot_head add last_debt decimal(24,6) DEFAULT NULL COMMENT '最终欠款' after debt;",
      locationLabel: '冻结迁移记录行',
      locationValue: 'migration-history/数据库更新记录:L1842-L1843',
      affectedObjectRefs: ['table:jsh_depot_head', 'field:debt', 'field:last_debt'],
      artifactDigest: 'sha256:d2e93166b0935166b86661061fa902324c0dbaa728b73eb26ddb677d022a4754',
    },
    {
      evidenceRef: 'github:tenancy:tenant-config-filter',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '租户表过滤规则',
      excerpt: '冻结租户规则记录：TenantConfig.doTableFilter；方法范围 L50–L67；记录表过滤规则入口与 TenantConfig 来源文件；完整方法体未保留。',
      locationLabel: '冻结租户规则记录',
      locationValue: 'jshERP-boot/src/main/java/com/jsh/erp/config/TenantConfig.java:L50-L67',
      affectedObjectRefs: ['rule:tenant-table-filter', 'config:TenantConfig'],
      artifactDigest: 'sha256:3d99eed49e65f2c8872983e3b31829a37c570e29377f973543d015a59894dfb1',
    },
    {
      evidenceRef: 'github:mapper:user-business-rights',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '用户业务权限 Mapper 记录',
      excerpt: '冻结 Mapper 记录：UserBusinessMapperEx 的基础数据授权查询；保存了 Mapper 文件、语句位置、涉及表和过滤标记；SQL 原文未保留。',
      locationLabel: '冻结 Mapper 结构记录',
      locationValue: 'jshERP-boot/src/main/resources/mapper_xml/UserBusinessMapperEx.xml:L15-L19',
      affectedObjectRefs: ['table:jsh_user_business', 'rule:basic-data-rights'],
      artifactDigest: 'sha256:c3b6519095559d5684083a0d9675e3e4be52ecef1e2d11cc6619e4c1199f6398',
    },
    {
      evidenceRef: 'github:service:serial-number',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '序列号服务记录',
      excerpt: '冻结服务记录：SerialNumberService.getSerialNumber；方法范围 L42–L50；记录序列号查询服务入口；完整方法体未保留。',
      locationLabel: '冻结服务方法记录',
      locationValue: 'jshERP-boot/src/main/java/com/jsh/erp/service/SerialNumberService.java:L42-L50',
      affectedObjectRefs: ['service:SerialNumberService.getSerialNumber', 'entity:SerialNumber'],
      artifactDigest: 'sha256:f6f59275e2e262ec6330d34a478070fde1cce3e058ee2e0e017da16df81104c8',
    },
    {
      evidenceRef: 'github:service:batch-number',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '批号库存明细查询记录',
      excerpt: '冻结服务记录：DepotItemService.getDepotItemByBatchNumber；方法范围 L829–L836；记录批号与库存明细的查询入口；完整方法体未保留。',
      locationLabel: '冻结服务方法记录',
      locationValue: 'jshERP-boot/src/main/java/com/jsh/erp/service/DepotItemService.java:L829-L836',
      affectedObjectRefs: ['service:DepotItemService.getDepotItemByBatchNumber', 'table:jsh_depot_item'],
      artifactDigest: 'sha256:b9b22399b486d68f3db6168bb2ce3cc29b15a7c19bb4a23d65fa0ea92ce4816f',
    },
    {
      evidenceRef: 'github:schema:material-current-stock',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '当前库存表 schema 记录',
      excerpt: '冻结 schema 记录：jsh_material_current_stock；源文件范围 L477–L489；保留表身份与行范围，未保留完整表定义文本。',
      locationLabel: '冻结 schema 记录',
      locationValue: 'schema/tables/jsh_material_current_stock.sql:L477-L489',
      affectedObjectRefs: ['table:jsh_material_current_stock'],
      artifactDigest: 'sha256:2fd65dc61e85d19c78c4bc298b9dcf5ba7fd91ab5c8fd549c2852ebb013514df',
    },
    {
      evidenceRef: 'github:schema:depot-item-allocation',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '调拨单据明细 schema 记录',
      excerpt: '冻结 schema 记录：jsh_depot_item；源文件范围 L182–L215；保留表身份和行范围，未保留完整建表 SQL。',
      locationLabel: '冻结 schema 记录',
      locationValue: 'schema/tables/jsh_depot_item.sql:L182-L215',
      affectedObjectRefs: ['table:jsh_depot_item', 'field:another_depot_id'],
      artifactDigest: 'sha256:d675cfc54eae142aa6fada6bb02183d2a2c75dc1fa346411646f95cee08c8e4d',
    },
    {
      evidenceRef: 'github:mapper:buy-or-sale-number',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '销售／采购数量 Mapper 记录',
      excerpt: '冻结 Mapper 记录：buyOrSaleNumber；保存语句名称、行范围、涉及表、聚合和过滤标记；SQL 原文未保留。',
      locationLabel: '冻结 Mapper 结构记录',
      locationValue: 'jshERP-boot/src/main/resources/mapper_xml/DepotItemMapperEx.xml:L567-L602',
      affectedObjectRefs: ['mapper:buyOrSaleNumber', 'table:jsh_depot_item'],
      artifactDigest: 'sha256:7c57e1d81cfb8ac2e0d620bbd2f5bf1d59e4f2535b98ee0f82e607f26c612c30',
    },
    {
      evidenceRef: 'github:mapper:buy-or-sale-total',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '销售／采购金额 Mapper 记录',
      excerpt: '冻结 Mapper 记录：buyOrSaleTotal；保存语句名称、行范围、涉及表、聚合和过滤标记；SQL 原文未保留。',
      locationLabel: '冻结 Mapper 结构记录',
      locationValue: 'jshERP-boot/src/main/resources/mapper_xml/DepotItemMapperEx.xml:L604-L639',
      affectedObjectRefs: ['mapper:buyOrSaleTotal', 'table:jsh_depot_item'],
      artifactDigest: 'sha256:7c57e1d81cfb8ac2e0d620bbd2f5bf1d59e4f2535b98ee0f82e607f26c612c30',
    },
    {
      evidenceRef: 'github:mapper:account-settlement',
      evidenceClass: 'FROZEN_RECORD',
      excerptKind: 'STRUCTURED_RECORD',
      title: '账户收支 Mapper 记录',
      excerpt: '冻结 Mapper 记录：AccountItemMapperEx 的账户收支汇总查询；保存语句位置、涉及表和聚合标记；SQL 原文未保留。',
      locationLabel: '冻结 Mapper 结构记录',
      locationValue: 'jshERP-boot/src/main/resources/mapper_xml/AccountItemMapperEx.xml:L24-L54',
      affectedObjectRefs: ['table:jsh_account_item', 'metric:account-settlement'],
      artifactDigest: 'sha256:1e7e2c8e89d36054a6a62c45ae98eb5378c1c58efec7a772846a326bb3b4a0c3',
    },
  ],
  traceLinks: [
    { linePrefix: '[TRACE:G01]', markdownAnchor: 'github-g01', evidenceRefs: ['github:schema:system-config-minus-stock'] },
    { linePrefix: '[TRACE:G02]', markdownAnchor: 'github-g02', evidenceRefs: ['github:schema:system-config-minus-stock'] },
    { linePrefix: '[TRACE:G03]', markdownAnchor: 'github-g03', evidenceRefs: ['github:service:minus-stock-flag', 'github:service:depot-head-minus-stock'] },
    { linePrefix: '[TRACE:G04]', markdownAnchor: 'github-g04', evidenceRefs: ['github:migration:jsh-depot-head-historical-status'] },
    { linePrefix: '[TRACE:G05]', markdownAnchor: 'github-g05', evidenceRefs: ['github:migration:jsh-depot-head-debt-fields'] },
    { linePrefix: '[TRACE:G06]', markdownAnchor: 'github-g06', evidenceRefs: ['github:tenancy:tenant-config-filter'] },
    { linePrefix: '[TRACE:G07]', markdownAnchor: 'github-g07', evidenceRefs: ['github:mapper:user-business-rights'] },
    { linePrefix: '[TRACE:G08]', markdownAnchor: 'github-g08', evidenceRefs: ['github:service:serial-number'] },
    { linePrefix: '[TRACE:G09]', markdownAnchor: 'github-g09', evidenceRefs: ['github:service:batch-number'] },
    { linePrefix: '[TRACE:G10]', markdownAnchor: 'github-g10', evidenceRefs: ['github:schema:material-current-stock'] },
    { linePrefix: '[TRACE:G11]', markdownAnchor: 'github-g11', evidenceRefs: ['github:schema:depot-item-allocation'] },
    { linePrefix: '[TRACE:G12]', markdownAnchor: 'github-g12', evidenceRefs: ['github:mapper:buy-or-sale-number'] },
    { linePrefix: '[TRACE:G13]', markdownAnchor: 'github-g13', evidenceRefs: ['github:mapper:buy-or-sale-total'] },
    { linePrefix: '[TRACE:G14]', markdownAnchor: 'github-g14', evidenceRefs: ['github:mapper:account-settlement'] },
  ],
} as const;
