import { useEffect, useState } from 'react';
import { Button, Drawer, Dropdown, Form, Input, Select, Space, Tag, Alert, message, Modal } from 'antd';
import { PlusOutlined, EditOutlined, MoreOutlined } from '@ant-design/icons';
import type { SemanticMetric, MetricType, CaliberFilter, ValidationIssue, Metric2WorkspaceData } from './mockData';
import { mockMetrics, mockEvents, caliberSummary, severityColor } from './mockData';
import { CaliberFilterBuilder } from './components';
import CompositeFormulaBuilder from './CompositeFormulaBuilder';
import { parseFormulaTokens } from './formulaUtils';
import { SemanticObjectTag } from '../../components/semantic-object-visuals';
import ResponsiveDataView, { ResponsiveDataCard } from '../../components/ResponsiveDataView';
import TechnicalDisclosure from '../../components/TechnicalDisclosure';

const OPERATORS = ['$sum', '$count', '$count_distinct', '$avg', '$max', '$min'];
const TYPE_LABEL = (t: MetricType) => (t === 'BASIC' ? '原子指标' : '复合指标');
const STATUS_LABEL: Record<string, string> = { ACTIVE: '启用', INACTIVE: '停用' };
const OPERATOR_LABEL: Record<string, string> = {
  $sum: '求和', $count: '计数', $count_distinct: '去重计数', $avg: '平均值', $max: '最大值', $min: '最小值',
};

let nextId = 3000;
const genId = () => ++nextId;

export default function MetricDefTab({ data, onChange, readOnly = false }: {
  data?: Metric2WorkspaceData;
  onChange?(data: Metric2WorkspaceData): void;
  readOnly?: boolean;
}) {
  const events = data?.events ?? mockEvents;
  const [metrics, setMetrics] = useState<SemanticMetric[]>(() => structuredClone(data?.metrics ?? mockMetrics));
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [editing, setEditing] = useState<SemanticMetric | null>(null);
  const [issues, setIssues] = useState<ValidationIssue[]>([]);
  useEffect(() => setMetrics(structuredClone(data?.metrics ?? mockMetrics)), [data?.metrics]);
  const commitMetrics = (update: (current: SemanticMetric[]) => SemanticMetric[]) => setMetrics((current) => {
    const next = update(current); if (data && onChange) onChange({ ...data, metrics: next }); return next;
  });

  const openNew = () => {
    setEditing({ id: 0, metricCode: '', metricName: '', metricType: 'BASIC', unit: '', eventId: events[0]?.id, eventName: events[0]?.eventName, baseAttributeCode: '', defaultOperator: '$sum', caliberFilter: { logic: 'AND', conditions: [] }, formula: '', formulaTokens: [], editability: 'EDITABLE', isAutoGenerated: false, status: 'ACTIVE' });
    setIssues([]);
    setDrawerOpen(true);
  };
  const openEdit = (m: SemanticMetric) => { setEditing({ ...m }); setIssues([]); setDrawerOpen(true); };
  const remove = (id: number) => { commitMetrics((ms) => ms.filter((m) => m.id !== id)); message.success('已删除'); };
  const copy = (m: SemanticMetric) => { commitMetrics((ms) => [...ms, { ...m, id: genId(), metricCode: m.metricCode + '_copy', metricName: m.metricName + '_副本', isAutoGenerated: false }]); message.success('已复制'); };

  const validate = (m: SemanticMetric): ValidationIssue[] => {
    const iss: ValidationIssue[] = [];
    if (!m.metricCode) iss.push({ severity: 'BLOCKER', checkCode: 'DUPLICATE_METRIC_CODE', message: '指标编码不能为空' });
    else if (metrics.some((x) => x.id !== m.id && x.metricCode === m.metricCode)) iss.push({ severity: 'BLOCKER', checkCode: 'DUPLICATE_METRIC_CODE', message: `指标编码"${m.metricCode}"已存在` });
    if (!m.metricName) iss.push({ severity: 'BLOCKER', checkCode: 'MISSING_METRIC_NAME', message: '指标名称不能为空' });
    if (m.metricType === 'BASIC') {
      if (!m.eventId) iss.push({ severity: 'BLOCKER', checkCode: 'MISSING_METRIC_EVENT', message: '原子指标必须选择事件' });
      if (!m.baseAttributeCode) iss.push({ severity: 'BLOCKER', checkCode: 'INVALID_BASE_ATTRIBUTE', message: '必须选择度量属性' });
      if (!m.defaultOperator) iss.push({ severity: 'BLOCKER', checkCode: 'INVALID_OPERATOR', message: '必须选择算子' });
      m.caliberFilter?.conditions.forEach((c) => {
        if (!c.attributeCode) iss.push({ severity: 'BLOCKER', checkCode: 'INVALID_CALIBER_ATTRIBUTE', message: '口径条件未选择属性' });
        if (c.values.length === 0 || c.values.every((v) => !v)) iss.push({ severity: 'WARNING', checkCode: 'INVALID_CALIBER_VALUE', message: `口径条件"${c.attributeCode}"未填写取值` });
      });
    } else {
      const tokens = m.formulaTokens || [];
      const metricTokens = tokens.filter((token) => token.type === 'METRIC');
      if (metricTokens.length === 0) iss.push({ severity: 'BLOCKER', checkCode: 'MISSING_FORMULA', message: '复合指标公式必须引用至少一个已保存的原子指标' });
      metricTokens.forEach((token) => {
        const ref = metrics.find((metric) => metric.id === token.metricId && metric.metricCode === token.metricCode);
        if (!ref) iss.push({ severity: 'BLOCKER', checkCode: 'INVALID_FORMULA_REFERENCE', message: `公式引用的指标不存在：${token.metricCode}` });
        else if (ref.id === m.id) iss.push({ severity: 'BLOCKER', checkCode: 'FORMULA_CIRCULAR_REF', message: '公式不能引用自身' });
        else if (ref.metricType !== 'BASIC') iss.push({ severity: 'BLOCKER', checkCode: 'INVALID_FORMULA_SOURCE', message: `复合指标只能引用原子指标：${ref.metricName}` });
      });
      const parsed = parseFormulaTokens(tokens);
      if (parsed.error) iss.push({ severity: 'BLOCKER', checkCode: 'INVALID_FORMULA_SYNTAX', message: parsed.error });
    }
    return iss;
  };

  const save = () => {
    if (!editing) return;
    const iss = validate(editing);
    setIssues(iss);
    if (iss.some((i) => i.severity === 'BLOCKER')) { message.error('存在阻断错误，未保存'); return; }
    if (editing.id === 0) {
      commitMetrics((ms) => [...ms, { ...editing, id: genId() }]);
      message.success('保存成功');
    } else {
      commitMetrics((ms) => ms.map((m) => (m.id === editing.id ? editing : m)));
      message.success('保存成功');
    }
    setDrawerOpen(false);
  };

  const setField = <K extends keyof SemanticMetric>(k: K, v: SemanticMetric[K]) => setEditing((e) => (e ? { ...e, [k]: v } : e));
  const actions = (metric: SemanticMetric) => readOnly ? <span style={{ color: '#8c8c8c' }}>只读</span> : <Space size={0}>
    <Button size="small" icon={<EditOutlined />} onClick={() => openEdit(metric)}>{metric.editability === 'READ_ONLY' ? '查看定义' : '编辑'}</Button>
    {metric.editability !== 'READ_ONLY' && <Dropdown trigger={['click']} menu={{
      items: [{ key: 'copy', label: '复制指标' }, { type: 'divider' }, { key: 'delete', label: '删除', danger: true }],
      onClick: ({ key }) => {
        if (key === 'copy') copy(metric);
        if (key === 'delete') Modal.confirm({ title: `删除指标“${metric.metricName}”？`, okText: '删除', okButtonProps: { danger: true }, cancelText: '取消', onOk: () => remove(metric.id) });
      },
    }}><Button type="text" size="small" icon={<MoreOutlined />} aria-label={`更多操作：${metric.metricName}`} /></Dropdown>}
  </Space>;
  const columns = [
    { title: '指标名称', dataIndex: 'metricName', width: 220, render: (name: string) => <Space size={6}><SemanticObjectTag kind="METRIC" />{name}</Space> },
    { title: '编码', dataIndex: 'metricCode', width: 190, render: (code: string) => <code className="technical-code-wrap">{code}</code> },
    { title: '类型', width: 180, render: (_: unknown, metric: SemanticMetric) => <Space size={4}><Tag>{TYPE_LABEL(metric.metricType)}</Tag>{metric.editability === 'READ_ONLY' && <Tag>只读口径</Tag>}</Space> },
    {
      title: '口径/公式', width: 360,
      render: (_: unknown, metric: SemanticMetric) => metric.metricType === 'BASIC'
        ? <span style={{ color: '#595959' }}>{caliberSummary(metric.caliberFilter)}</span>
        : <code>{metric.formula}</code>,
    },
    { title: '来源', dataIndex: 'isAutoGenerated', width: 110, render: (auto: boolean) => (auto ? <Tag>自动生成</Tag> : <Tag color="cyan">自定义</Tag>) },
    { title: '状态', dataIndex: 'status', width: 100, render: (status: string) => <Tag color={status === 'ACTIVE' ? 'green' : 'default'}>{STATUS_LABEL[status] ?? '待确认'}</Tag> },
    { title: '操作', width: 132, fixed: 'right' as const, render: (_: unknown, metric: SemanticMetric) => actions(metric) },
  ];

  return (
    <div>
      {!readOnly && <Button type="primary" icon={<PlusOutlined />} onClick={openNew} style={{ marginBottom: 12 }}>新建指标</Button>}
      <ResponsiveDataView
        ariaLabel="指标列表"
        rowKey="id"
        dataSource={metrics}
        pagination={{ pageSize: 20, showSizeChanger: false }}
        columns={columns}
        minTableWidth={1292}
        renderCard={(metric) => <ResponsiveDataCard
          title={<Space size={6}><SemanticObjectTag kind="METRIC" />{metric.metricName}</Space>}
          subtitle={<code>{metric.metricCode}</code>}
          status={<Tag color={metric.status === 'ACTIVE' ? 'green' : 'default'}>{STATUS_LABEL[metric.status] ?? '待确认'}</Tag>}
          fields={[
            { label: '类型', value: <Space size={4}><Tag>{TYPE_LABEL(metric.metricType)}</Tag>{metric.editability === 'READ_ONLY' && <Tag>只读口径</Tag>}</Space> },
            { label: '来源', value: metric.isAutoGenerated ? '自动生成' : '自定义' },
            { label: '口径/公式', value: metric.metricType === 'BASIC' ? caliberSummary(metric.caliberFilter) : <code>{metric.formula}</code>, wide: true },
          ]}
          actions={actions(metric)}
        />}
      />

      <Drawer
        title={editing?.id === 0 ? '新建指标' : editing?.editability === 'READ_ONLY' ? `指标定义：${editing.metricName}` : `编辑指标：${editing?.metricName}`}
        open={drawerOpen}
        onClose={() => setDrawerOpen(false)}
        width="min(980px, 100vw)"
        footer={<Space style={{ width: '100%', justifyContent: 'flex-end' }}><Button onClick={() => setDrawerOpen(false)}>{editing?.editability === 'READ_ONLY' ? '关闭' : '取消'}</Button>{editing?.editability !== 'READ_ONLY' && <Button type="primary" onClick={save}>保存</Button>}</Space>}
      >
        {editing && (
          <Form layout="vertical" disabled={editing.editability === 'READ_ONLY'}>
            {editing.editability === 'READ_ONLY' && <Alert type="info" showIcon style={{ marginBottom: 16 }} message="该指标来自已发布模型，公式和依赖保持只读" description={editing.compatibilityReason || '如需调整，请在个人草稿中创建可编辑指标并重新审核。'} />}
            <Form.Item label="指标名称" required>
              <Input value={editing.metricName} onChange={(e) => setField('metricName', e.target.value)} />
            </Form.Item>
            <Form.Item label="指标编码（技术标识）" required>
              <Input value={editing.metricCode} onChange={(e) => setField('metricCode', e.target.value)} disabled={editing.id !== 0} />
            </Form.Item>
            <Space>
              <Form.Item label="指标类型" required style={{ minWidth: 200 }}>
                <Select value={editing.metricType} onChange={(metricType: MetricType) => setEditing((metric) => metric ? metricType === 'COMPOSITE'
                  ? { ...metric, metricType, eventId: undefined, eventName: undefined, baseAttributeCode: undefined, defaultOperator: undefined, caliberFilter: undefined, formula: '', formulaTokens: [], formulaExpression: undefined }
                  : { ...metric, metricType, eventId: events[0]?.id, eventName: events[0]?.eventName, baseAttributeCode: events[0]?.attributes.find((attribute) => attribute.isMetric)?.attributeCode ?? '', defaultOperator: '$sum', caliberFilter: { logic: 'AND', conditions: [] }, formula: undefined, formulaTokens: undefined, formulaExpression: undefined }
                  : metric)}
                  options={[{ value: 'BASIC', label: '原子指标' }, { value: 'COMPOSITE', label: '复合指标' }]} />
              </Form.Item>
              <Form.Item label="单位">
                <Input value={editing.unit} onChange={(e) => setField('unit', e.target.value)} style={{ width: 120 }} />
              </Form.Item>
            </Space>

            {editing.metricType === 'BASIC' ? (
              <>
                <Form.Item label="关联事件" required>
                  <Select value={editing.eventId} onChange={(v) => {
                    const ev = events.find((e) => e.id === v)!;
                    setEditing((e) => e ? { ...e, eventId: v, eventName: ev.eventName, baseAttributeCode: ev.attributes.find((a) => a.isMetric)?.attributeCode ?? '' } : e);
                  }}
                    options={events.map((e) => ({ value: e.id, label: `${e.eventName}(${e.eventCode})` }))} />
                </Form.Item>
                <Space style={{ width: '100%' }}>
                  <Form.Item label="度量属性" required style={{ minWidth: 260 }}>
                    <Select value={editing.baseAttributeCode} onChange={(v) => setField('baseAttributeCode', v)}
                      options={events.find((e) => e.id === editing.eventId)?.attributes.filter((a) => a.isMetric).map((a) => ({ value: a.attributeCode, label: `${a.attributeName}(${a.attributeCode})` })) ?? []} />
                  </Form.Item>
                  <Form.Item label="默认算子" required>
                    <Select value={editing.defaultOperator} onChange={(v) => setField('defaultOperator', v)} style={{ width: 160 }}
                      options={OPERATORS.map((o) => ({ value: o, label: OPERATOR_LABEL[o] ?? o }))} />
                  </Form.Item>
                </Space>
                <Form.Item label="业务口径筛选">
                  <CaliberFilterBuilder value={editing.caliberFilter ?? { logic: 'AND', conditions: [] }} eventId={editing.eventId} events={events}
                    onChange={(v: CaliberFilter) => setField('caliberFilter', v)} />
                </Form.Item>
                <TechnicalDisclosure><p>口径条件使用语义属性编码，运行时通过字段映射转换为物理查询条件。配置随指标一并保存。</p></TechnicalDisclosure>
              </>
            ) : (
              <>
                <Form.Item label="计算逻辑" required>
                  <CompositeFormulaBuilder
                    key={editing.id}
                    metrics={metrics.filter((metric) => metric.metricType === 'BASIC' && metric.id !== editing.id)}
                    value={editing.formulaTokens || []}
                    onChange={(formulaTokens, formula, formulaExpression) => setEditing((metric) => metric
                      ? { ...metric, formulaTokens, formula, formulaExpression }
                      : metric)}
                  />
                </Form.Item>
                <TechnicalDisclosure><p>计算结构保存为指标引用与表达式树；复合指标继承其引用原子指标的口径。</p></TechnicalDisclosure>
              </>
            )}
          </Form>
        )}

        {issues.length > 0 && (
          <div style={{ marginTop: 16 }}>
            {issues.map((iss, i) => (
              <Alert key={i} type={iss.severity === 'BLOCKER' ? 'error' : iss.severity === 'WARNING' ? 'warning' : 'info'} showIcon
                style={{ marginBottom: 8 }}
                message={<><Tag color={severityColor(iss.severity)}>{iss.severity === 'BLOCKER' ? '必须修正' : '请确认'}</Tag>{iss.message}</>} />
            ))}
          </div>
        )}
      </Drawer>
    </div>
  );
}
