import type { ReactNode } from 'react';

/* ============ 基础枚举 ============ */
export type MetricType = 'BASIC' | 'COMPOSITE';
export type RuleMode = 'COMPARISON' | 'FILTER' | 'COMPOSITE';
export type TargetObjectType = 'METRIC' | 'ENTITY' | 'EVENT';
export type CalibOp = '=' | '!=' | '>' | '>=' | '<' | '<=' | 'IN';
export type LogicOp = 'AND' | 'OR';
export type TargetType = 'AMOUNT' | 'RATIO';
export type TimePeriod = 'MONTHLY' | 'QUARTERLY' | 'YEARLY';
export type Status = 'ACTIVE' | 'INACTIVE';

/* ============ 事件 / 实体 / 关系 ============ */
export interface ObjAttribute {
  attributeCode: string;
  attributeName: string;
  dataType: 'STRING' | 'NUMBER' | 'DECIMAL' | 'DATETIME' | 'ENUM' | 'BOOLEAN';
  semanticType: 'IDENTIFIER' | 'DIMENSION' | 'MEASURE' | 'TIME' | 'TEXT';
  isFilterable: boolean;
  isMetric?: boolean;
  aggregateOperator?: 'SUM' | 'COUNT' | 'AVG' | 'MAX' | 'MIN';
  enumValues?: string[];
}

export interface SemanticEvent {
  id: number;
  eventCode: string;
  eventName: string;
  attributes: ObjAttribute[];
}

export interface SemanticEntity {
  id: number;
  entityCode: string;
  entityName: string;
  attributes: ObjAttribute[];
}

export interface SemanticRelation {
  id: number;
  sourceType: 'EVENT' | 'ENTITY';
  sourceId: number;
  targetType: 'EVENT' | 'ENTITY';
  targetId: number;
  relationRole: string;
}

/* ============ 条件（单对象属性条件，caliber_filter 与 FILTER 共用） ============ */
export interface CaliberCondition {
  attributeCode: string;
  attributeName?: string;
  op: CalibOp;
  values: string[];
}
export interface CaliberFilter {
  logic: LogicOp;
  conditions: CaliberCondition[];
}

export type FormulaTokenType = 'METRIC' | 'OP' | 'NUM' | 'LPAREN' | 'RPAREN';
export type FormulaOperator = '+' | '-' | '*' | '/';

export interface FormulaToken {
  type: FormulaTokenType;
  value: string;
  metricId?: number;
  metricCode?: string;
  metricName?: string;
}

export type FormulaExpression =
  | { type: 'METRIC'; metricId: number; metricCode: string }
  | { type: 'NUMBER'; value: number }
  | { type: 'BINARY'; operator: FormulaOperator; left: FormulaExpression; right: FormulaExpression };

export interface ComparisonExpression {
  operator: '<' | '<=' | '>' | '>=' | '=' | '!=';
  ratio?: number; // 达成线，默认 1：actual (operator) (target_value * ratio)
}

export interface CompositeComponent {
  subRuleId: number;
  isNegated: boolean;
  sortOrder: number;
}

/* ============ 指标 ============ */
export interface SemanticMetric {
  id: number;
  metricCode: string;
  metricName: string;
  metricType: MetricType;
  unit?: string;
  description?: string;
  eventId?: number;
  eventName?: string;
  baseAttributeCode?: string;
  defaultOperator?: string;
  caliberFilter?: CaliberFilter;
  formula?: string;
  formulaTokens?: FormulaToken[];
  formulaExpression?: FormulaExpression;
  editability?: 'EDITABLE' | 'READ_ONLY';
  compatibilityReason?: string;
  isAutoGenerated: boolean;
  status: Status;
}

/* ============ 业务规则（三模式，每条挂一个语义对象） ============ */
export interface BusinessRule {
  id: number;
  ruleCode: string;
  ruleName: string;
  ruleType: RuleMode;
  targetObjectType: TargetObjectType;
  targetObjectId: number;
  targetObjectName: string;
  expression: ComparisonExpression | CaliberFilter | null; // COMPARISON | FILTER | null(COMPOSITE)
  logicOperator?: LogicOp;
  components?: CompositeComponent[];
  isNegative: boolean;
  oppositeRuleId?: number;
  triggerWords: string[];
  description?: string;
  status: Status;
}

export interface ReadOnlyRuleCandidate {
  id: number;
  ruleCode: string;
  ruleName: string;
  description: string;
  targetObjectType?: TargetObjectType;
  targetObjectId?: number;
  targetObjectName?: string;
  evidenceRefs: string[];
  status: 'NEEDS_STRUCTURE' | 'UNRESOLVED_TARGET';
}

/* ============ 目标值 ============ */
export interface DimensionItem {
  entityCode: string;
  valueCode: string;
}
export interface DimensionFilter {
  dimensions: DimensionItem[];
}
export interface MetricTarget {
  id: number;
  metricId: number;
  metricName: string;
  targetType: TargetType;
  targetValue: number;
  dimensionFilter: DimensionFilter;
  timePeriod: TimePeriod;
  effectiveDate: string;
  description?: string;
  status: Status;
}

export interface ValidationIssue {
  severity: 'BLOCKER' | 'WARNING' | 'INFO';
  checkCode: string;
  message: string;
}

/* ============ Mock 数据 ============ */
export const mockEvents: SemanticEvent[] = [
  {
    id: 100, eventCode: 'order_event', eventName: '订单事件',
    attributes: [
      { attributeCode: 'order_id', attributeName: '订单ID', dataType: 'STRING', semanticType: 'IDENTIFIER', isFilterable: false },
      { attributeCode: 'amount', attributeName: '金额', dataType: 'DECIMAL', semanticType: 'MEASURE', isFilterable: true, isMetric: true, aggregateOperator: 'SUM' },
      { attributeCode: 'gross_profit', attributeName: '毛利', dataType: 'DECIMAL', semanticType: 'MEASURE', isFilterable: true, isMetric: true, aggregateOperator: 'SUM' },
      { attributeCode: 'order_status', attributeName: '订单状态', dataType: 'ENUM', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['completed', 'pending', 'cancelled', 'refunded'] },
      { attributeCode: 'is_tax_included', attributeName: '是否含税', dataType: 'BOOLEAN', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['0', '1'] },
      { attributeCode: 'pay_time', attributeName: '支付时间', dataType: 'DATETIME', semanticType: 'TIME', isFilterable: true },
    ],
  },
  {
    id: 101, eventCode: 'refund_event', eventName: '退款事件',
    attributes: [
      { attributeCode: 'refund_id', attributeName: '退款ID', dataType: 'STRING', semanticType: 'IDENTIFIER', isFilterable: false },
      { attributeCode: 'refund_amount', attributeName: '退款金额', dataType: 'DECIMAL', semanticType: 'MEASURE', isFilterable: true, isMetric: true, aggregateOperator: 'SUM' },
      { attributeCode: 'refund_time', attributeName: '退款时间', dataType: 'DATETIME', semanticType: 'TIME', isFilterable: true },
    ],
  },
];

export const mockEntities: SemanticEntity[] = [
  {
    id: 200, entityCode: 'store', entityName: '门店',
    attributes: [
      { attributeCode: 'store_id', attributeName: '门店ID', dataType: 'STRING', semanticType: 'IDENTIFIER', isFilterable: false },
      { attributeCode: 'store_name', attributeName: '门店名称', dataType: 'STRING', semanticType: 'DIMENSION', isFilterable: true },
      { attributeCode: 'store_level', attributeName: '门店等级', dataType: 'ENUM', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['A', 'B', 'C'] },
      { attributeCode: 'region', attributeName: '区域', dataType: 'ENUM', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['华东', '华南', '华北', '华中'] },
    ],
  },
  {
    id: 300, entityCode: 'geo', entityName: '区域',
    attributes: [
      { attributeCode: 'geo_code', attributeName: '区域编码', dataType: 'STRING', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['EAST', 'SOUTH', 'NORTH', 'WEST'] },
      { attributeCode: 'geo_name', attributeName: '区域名称', dataType: 'STRING', semanticType: 'DIMENSION', isFilterable: true },
    ],
  },
  {
    id: 400, entityCode: 'customer', entityName: '客户',
    attributes: [
      { attributeCode: 'customer_id', attributeName: '客户ID', dataType: 'STRING', semanticType: 'IDENTIFIER', isFilterable: false },
      { attributeCode: 'customer_level', attributeName: '客户等级', dataType: 'ENUM', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['VIP', 'HIGH', 'MID', 'LOW'] },
      { attributeCode: 'purchase_count_90d', attributeName: '近90天订单数', dataType: 'NUMBER', semanticType: 'MEASURE', isFilterable: true },
    ],
  },
  {
    id: 500, entityCode: 'product', entityName: '商品',
    attributes: [
      { attributeCode: 'product_id', attributeName: '商品ID', dataType: 'STRING', semanticType: 'IDENTIFIER', isFilterable: false },
      { attributeCode: 'category', attributeName: '品类', dataType: 'ENUM', semanticType: 'DIMENSION', isFilterable: true, enumValues: ['womens', 'mens', 'digital', 'food'] },
    ],
  },
];

export const mockRelations: SemanticRelation[] = [
  { id: 1, sourceType: 'EVENT', sourceId: 100, targetType: 'ENTITY', targetId: 200, relationRole: 'store' },
  { id: 2, sourceType: 'ENTITY', sourceId: 200, targetType: 'ENTITY', targetId: 300, relationRole: 'belongs_to' },
  { id: 3, sourceType: 'EVENT', sourceId: 100, targetType: 'ENTITY', targetId: 400, relationRole: 'buyer' },
  { id: 4, sourceType: 'EVENT', sourceId: 100, targetType: 'ENTITY', targetId: 500, relationRole: 'sku' },
];

/* 从某 event 出发 BFS 可达实体（用于目标值 dimension_filter） */
export function reachableEntities(eventId: number): SemanticEntity[] {
  const visited = new Set<number>();
  const queue: { id: number; type: 'EVENT' | 'ENTITY' }[] = [{ id: eventId, type: 'EVENT' }];
  const result: SemanticEntity[] = [];
  while (queue.length) {
    const node = queue.shift()!;
    for (const r of mockRelations) {
      if (r.sourceType === node.type && r.sourceId === node.id && !visited.has(r.targetId)) {
        visited.add(r.targetId);
        const ent = mockEntities.find((e) => e.id === r.targetId);
        if (ent) result.push(ent);
        queue.push({ id: r.targetId, type: 'ENTITY' });
      }
    }
  }
  return result;
}

export function metricRootEventId(m: SemanticMetric): number | undefined {
  if (m.metricType === 'BASIC') return m.eventId;
  if (m.formulaTokens) {
    for (const token of m.formulaTokens) {
      if (token.type !== 'METRIC') continue;
      const ref = mockMetrics.find((x) => x.id === token.metricId || x.metricCode === token.metricCode);
      if (ref?.eventId) return ref.eventId;
    }
  }
  if (m.formula) {
    const codes = m.formula.match(/[a-z_]+/g) || [];
    for (const code of codes) {
      const ref = mockMetrics.find((x) => x.metricCode === code);
      if (ref?.eventId) return ref.eventId;
    }
  }
  return undefined;
}

export const mockMetrics: SemanticMetric[] = [
  { id: 2001, metricCode: 'sales_amount', metricName: '销售额', metricType: 'BASIC', unit: '元', eventId: 100, eventName: '订单事件', baseAttributeCode: 'amount', defaultOperator: '$sum', isAutoGenerated: true, status: 'ACTIVE' },
  { id: 2002, metricCode: 'order_count', metricName: '订单数', metricType: 'BASIC', unit: '笔', eventId: 100, eventName: '订单事件', baseAttributeCode: 'order_id', defaultOperator: '$count', isAutoGenerated: true, status: 'ACTIVE' },
  { id: 2004, metricCode: 'gmv', metricName: 'GMV', metricType: 'BASIC', unit: '元', eventId: 100, eventName: '订单事件', baseAttributeCode: 'amount', defaultOperator: '$sum', isAutoGenerated: false, status: 'ACTIVE', caliberFilter: { logic: 'AND', conditions: [{ attributeCode: 'order_status', op: 'IN', values: ['completed', 'pending'] }] } },
  { id: 2003, metricCode: 'valid_sales', metricName: '有效销售额', metricType: 'BASIC', unit: '元', eventId: 100, eventName: '订单事件', baseAttributeCode: 'amount', defaultOperator: '$sum', isAutoGenerated: false, status: 'ACTIVE', caliberFilter: { logic: 'AND', conditions: [{ attributeCode: 'order_status', op: '=', values: ['completed'] }] } },
  { id: 2005, metricCode: 'gross_profit', metricName: '毛利润', metricType: 'BASIC', unit: '元', eventId: 100, eventName: '订单事件', baseAttributeCode: 'gross_profit', defaultOperator: '$sum', isAutoGenerated: false, status: 'ACTIVE' },
  {
    id: 2011, metricCode: 'gross_margin', metricName: '毛利率', metricType: 'COMPOSITE', unit: '%', isAutoGenerated: false, status: 'ACTIVE',
    formula: 'gross_profit / sales_amount',
    formulaTokens: [
      { type: 'METRIC', value: 'gross_profit', metricId: 2005, metricCode: 'gross_profit', metricName: '毛利润' },
      { type: 'OP', value: '/' },
      { type: 'METRIC', value: 'sales_amount', metricId: 2001, metricCode: 'sales_amount', metricName: '销售额' },
    ],
    formulaExpression: { type: 'BINARY', operator: '/', left: { type: 'METRIC', metricId: 2005, metricCode: 'gross_profit' }, right: { type: 'METRIC', metricId: 2001, metricCode: 'sales_amount' } },
  },
  {
    id: 2012, metricCode: 'avg_order_value', metricName: '客单价', metricType: 'COMPOSITE', unit: '元', isAutoGenerated: false, status: 'ACTIVE',
    formula: 'sales_amount / order_count',
    formulaTokens: [
      { type: 'METRIC', value: 'sales_amount', metricId: 2001, metricCode: 'sales_amount', metricName: '销售额' },
      { type: 'OP', value: '/' },
      { type: 'METRIC', value: 'order_count', metricId: 2002, metricCode: 'order_count', metricName: '订单数' },
    ],
    formulaExpression: { type: 'BINARY', operator: '/', left: { type: 'METRIC', metricId: 2001, metricCode: 'sales_amount' }, right: { type: 'METRIC', metricId: 2002, metricCode: 'order_count' } },
  },
];

export const mockRules: BusinessRule[] = [
  // COMPARISON（挂 METRIC）
  { id: 1601, ruleCode: 'achieve', ruleName: '达标', ruleType: 'COMPARISON', targetObjectType: 'METRIC', targetObjectId: 2001, targetObjectName: '销售额', expression: { operator: '>=', ratio: 0.95 }, isNegative: false, oppositeRuleId: 1602, triggerWords: ['达标', '完成', '达到目标'], description: '实际>=目标*95%', status: 'ACTIVE' },
  { id: 1602, ruleCode: 'not_achieve', ruleName: '未达标', ruleType: 'COMPARISON', targetObjectType: 'METRIC', targetObjectId: 2001, targetObjectName: '销售额', expression: { operator: '>=', ratio: 0.95 }, isNegative: true, oppositeRuleId: 1601, triggerWords: ['未达标', '没达标', '不达标'], description: '实际<目标*95%', status: 'ACTIVE' },
  { id: 1801, ruleCode: 'high_avg_order', ruleName: '高客单', ruleType: 'COMPARISON', targetObjectType: 'METRIC', targetObjectId: 2012, targetObjectName: '客单价', expression: { operator: '>', ratio: 1 }, isNegative: false, triggerWords: ['高客单', '大额订单'], description: '客单价>500', status: 'ACTIVE' },
  // FILTER（挂 ENTITY，单对象属性条件）
  { id: 1701, ruleCode: 'core_store', ruleName: '核心店', ruleType: 'FILTER', targetObjectType: 'ENTITY', targetObjectId: 200, targetObjectName: '门店', expression: { logic: 'AND', conditions: [{ attributeCode: 'store_level', op: 'IN', values: ['A', 'B'] }] }, isNegative: false, triggerWords: ['核心店', '重点店', '主力店'], description: '门店等级A/B', status: 'ACTIVE' },
  { id: 1702, ruleCode: 'east_core_store', ruleName: '华东区核心店', ruleType: 'FILTER', targetObjectType: 'ENTITY', targetObjectId: 200, targetObjectName: '门店', expression: { logic: 'AND', conditions: [{ attributeCode: 'store_level', op: 'IN', values: ['A', 'B'] }, { attributeCode: 'region', op: '=', values: ['华东'] }] }, isNegative: false, triggerWords: ['华东核心店'], description: '华东区等级A/B门店', status: 'ACTIVE' },
  { id: 1703, ruleCode: 'vip_customer', ruleName: 'VIP客户', ruleType: 'FILTER', targetObjectType: 'ENTITY', targetObjectId: 400, targetObjectName: '客户', expression: { logic: 'AND', conditions: [{ attributeCode: 'customer_level', op: '=', values: ['VIP'] }] }, isNegative: false, triggerWords: ['VIP客户', 'VIP'], description: '客户等级=VIP', status: 'ACTIVE' },
  { id: 1902, ruleCode: 'high_repurchase', ruleName: '高复购', ruleType: 'FILTER', targetObjectType: 'ENTITY', targetObjectId: 400, targetObjectName: '客户', expression: { logic: 'AND', conditions: [{ attributeCode: 'purchase_count_90d', op: '>=', values: ['2'] }] }, isNegative: false, triggerWords: ['高复购', '复购客户'], description: '近90天订单数>=2', status: 'ACTIVE' },
  // COMPOSITE（只组合 FILTER）
  { id: 1950, ruleCode: 'premium_customer', ruleName: '优质客户', ruleType: 'COMPOSITE', targetObjectType: 'ENTITY', targetObjectId: 400, targetObjectName: '客户', expression: null, logicOperator: 'AND', components: [{ subRuleId: 1703, isNegated: false, sortOrder: 0 }, { subRuleId: 1902, isNegated: false, sortOrder: 1 }], isNegative: false, triggerWords: ['优质客户'], description: 'VIP AND 高复购', status: 'ACTIVE' },
];

export const mockTargets: MetricTarget[] = [
  { id: 1501, metricId: 2001, metricName: '销售额', targetType: 'AMOUNT', targetValue: 30000, dimensionFilter: { dimensions: [{ entityCode: 'geo', valueCode: 'EAST' }] }, timePeriod: 'MONTHLY', effectiveDate: '2026-05-01', description: '华东区5月销售目标', status: 'ACTIVE' },
  { id: 1502, metricId: 2001, metricName: '销售额', targetType: 'AMOUNT', targetValue: 50000, dimensionFilter: { dimensions: [{ entityCode: 'geo', valueCode: 'SOUTH' }] }, timePeriod: 'MONTHLY', effectiveDate: '2026-05-01', description: '华南区5月销售目标', status: 'ACTIVE' },
  { id: 1503, metricId: 2001, metricName: '销售额', targetType: 'AMOUNT', targetValue: 500000, dimensionFilter: { dimensions: [] }, timePeriod: 'YEARLY', effectiveDate: '2026-01-01', description: '全局年度销售目标', status: 'ACTIVE' },
  { id: 1504, metricId: 2012, metricName: '客单价', targetType: 'AMOUNT', targetValue: 500, dimensionFilter: { dimensions: [] }, timePeriod: 'MONTHLY', effectiveDate: '2026-05-01', description: '客单价目标(高客单阈值)', status: 'ACTIVE' },
];

/* 模式 × 对象 适用矩阵 */
export const MODE_OBJECT_MATRIX: Record<RuleMode, TargetObjectType[]> = {
  COMPARISON: ['METRIC'],
  FILTER: ['ENTITY', 'EVENT'],
  COMPOSITE: ['ENTITY', 'EVENT'], // 只组合 FILTER，故与 FILTER 同对象域
};

export const OPERATORS: CalibOp[] = ['=', '!=', '>', '>=', '<', '<=', 'IN'];

export function severityColor(s: ValidationIssue['severity']): string {
  return s === 'BLOCKER' ? 'red' : s === 'WARNING' ? 'orange' : 'blue';
}

export function caliberSummary(f?: CaliberFilter): string {
  if (!f || f.conditions.length === 0) return '-（全部数据，无口径）';
  return f.conditions
    .map((c) => `${c.attributeCode} ${c.op} ${c.op === 'IN' ? `(${c.values.join(',')})` : c.values[0] ?? ''}`)
    .join(` ${f.logic} `);
}

export function targetObjectLabel(t: TargetObjectType): string {
  return t === 'METRIC' ? '指标' : t === 'ENTITY' ? '实体' : '事件';
}

/* 取某对象（实体或事件）的可筛选属性，供 FILTER 条件构建器 */
export function filterableAttrs(objType: TargetObjectType, objId: number): ObjAttribute[] {
  if (objType === 'ENTITY') return mockEntities.find((e) => e.id === objId)?.attributes.filter((a) => a.isFilterable) ?? [];
  if (objType === 'EVENT') return mockEvents.find((e) => e.id === objId)?.attributes.filter((a) => a.isFilterable) ?? [];
  return [];
}

export type Metric2WorkspaceData = {
  events: SemanticEvent[];
  entities: SemanticEntity[];
  relations: SemanticRelation[];
  metrics: SemanticMetric[];
  rules: BusinessRule[];
  ruleCandidates?: ReadOnlyRuleCandidate[];
  targets: MetricTarget[];
};

const originalMetric2Data: Metric2WorkspaceData = structuredClone({
  events: mockEvents,
  entities: mockEntities,
  relations: mockRelations,
  metrics: mockMetrics,
  rules: mockRules,
  targets: mockTargets,
});
let currentRuleCandidates: ReadOnlyRuleCandidate[] = [];

export function normalizeMetric2WorkspaceData(data: Metric2WorkspaceData): Metric2WorkspaceData {
  const source = structuredClone(data);
  const legacyCandidates = source.rules.filter((rule) => rule.description?.startsWith('待结构化规则候选：'));
  source.rules = source.rules.filter((rule) => !legacyCandidates.includes(rule));
  if (!source.ruleCandidates?.length && legacyCandidates.length) {
    source.ruleCandidates = legacyCandidates.map((rule) => ({
      id: rule.id,
      ruleCode: rule.ruleCode || `legacy-rule-${rule.id}`,
      ruleName: rule.ruleName || '历史规则候选',
      description: rule.description?.replace(/^待结构化规则候选：/, '') || '历史候选内容未完整保留。',
      evidenceRefs: [],
      status: 'UNRESOLVED_TARGET',
    }));
  }
  source.ruleCandidates ??= [];
  return source;
}

export function replaceMetric2WorkspaceData(data?: Metric2WorkspaceData) {
  const source = normalizeMetric2WorkspaceData(data ?? originalMetric2Data);
  mockEvents.splice(0, mockEvents.length, ...structuredClone(source.events));
  mockEntities.splice(0, mockEntities.length, ...structuredClone(source.entities));
  mockRelations.splice(0, mockRelations.length, ...structuredClone(source.relations));
  mockMetrics.splice(0, mockMetrics.length, ...structuredClone(source.metrics));
  mockRules.splice(0, mockRules.length, ...structuredClone(source.rules));
  currentRuleCandidates = structuredClone(source.ruleCandidates ?? []);
  mockTargets.splice(0, mockTargets.length, ...structuredClone(source.targets));
}

export function readMetric2WorkspaceData(): Metric2WorkspaceData {
  return structuredClone({
    events: mockEvents, entities: mockEntities, relations: mockRelations,
    metrics: mockMetrics, rules: mockRules, ruleCandidates: currentRuleCandidates, targets: mockTargets,
  });
}

export type AnyNode = ReactNode;
