export type CalendarType = 'NATURAL' | 'FISCAL' | 'RETAIL_445' | 'CUSTOM';
export type RangeType = 'CURRENT' | 'PREVIOUS' | 'ROLLING' | 'SINCE_START' | 'HOLIDAY' | 'CUSTOM' | 'ABSOLUTE';
export type Granularity = 'YEAR' | 'QUARTER' | 'MONTH' | 'WEEK' | 'DAY';
export interface ObjectAttribute {
  id: number;
  attributeCode: string;
  attributeName: string;
  synonyms?: string[];
  dataType: string;
  semanticType: SemanticType;
  isFilterable: boolean;
  isGroupable?: boolean;
  isDisplay?: boolean;
  isPrimaryTime?: boolean;
  isMetric?: boolean;
  aggregateOperator?: 'SUM' | 'AVG' | 'COUNT' | 'COUNT_DISTINCT' | 'MAX' | 'MIN';
  enumValues?: string[];
  unit?: string;
  formatPattern?: string;
}
export type HolidayType = 'LEGAL' | 'ENTERPRISE' | 'CUSTOM';

export type TargetType = 'METRIC' | 'ENTITY' | 'EVENT' | 'ATTRIBUTE' | 'DIMENSION' | 'RULE' | 'VALUE' | 'TIME_RULE' | 'TERM';
export type AliasSource = 'MANUAL' | 'DISCOVERY' | 'UNKNOWN_TERM' | 'IMPORT';
export type ConflictStatus = 'NONE' | 'CONFLICTED' | 'RESOLVED';

export type TermRelatedObjectType = 'METRIC' | 'ENTITY' | 'EVENT' | 'TERM' | 'ALIAS';

export type SemanticType =
  | 'AMOUNT'
  | 'NUMBER'
  | 'RATIO'
  | 'DATE'
  | 'DATETIME'
  | 'TIME'
  | 'BOOLEAN'
  | 'TEXT'
  | 'CODE'
  | 'ENUM'
  | 'HIERARCHY'
  | 'LIFECYCLE'
  | 'ID'
  | 'FOREIGN_KEY';

export interface TimeCalendar {
  id: number;
  calendarCode: string;
  calendarName: string;
  calendarType: CalendarType;
  yearStartMonth: number;
  yearStartDay: number;
  description?: string;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface TimeRule {
  id: number;
  ruleCode: string;
  ruleText: string;
  calendarCode: string;
  granularity: Granularity;
  rangeType: RangeType;
  offsetValue: number;
  rollingDays?: number;
  holidayCode?: string;
  offsetStart?: number;
  offsetEnd?: number;
  paramPattern?: string;
  paramDefault?: number;
  fixedStartDate?: string;
  fixedEndDate?: string;
  isRecurring?: boolean;
  explanationTemplate?: string;
  priority: number;
  participateInReasoning: boolean;
  isAutoGenerated: boolean;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface HolidayCalendar {
  id: number;
  holidayCode: string;
  holidayName: string;
  holidayType: HolidayType;
  countryCode?: string;
  description?: string;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface HolidayPeriod {
  id: number;
  holidayCalendarId: number;
  year: number;
  startDate: string;
  endDate: string;
  workdayAdjustments: { date: string; description: string }[];
}

export interface SemanticEntity {
  id: number;
  entityCode: string;
  entityName: string;
  synonyms?: string[];
  description?: string;
  owner?: string;
  uniqueIdentifierAttributeId?: number;
  defaultTimeAttributeId?: number;
  status?: 'ACTIVE' | 'INACTIVE';
  attributes: ObjectAttribute[];
}

export interface SemanticEvent {
  id: number;
  eventCode: string;
  eventName: string;
  synonyms?: string[];
  description?: string;
  owner?: string;
  uniqueIdentifierAttributeId?: number;
  defaultTimeAttributeId?: number;
  status?: 'ACTIVE' | 'INACTIVE';
  attributes: ObjectAttribute[];
}

export interface EntityHierarchyLevel {
  id: number;
  objectType: 'EVENT' | 'ENTITY';
  objectId: number;
  attributeId: number;
  hierarchyCode: string;
  hierarchyName: string;
  levelCode: string;
  levelName: string;
  levelDepth: number;
  parentLevelId?: number;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface ObjectValue {
  id: number;
  objectType: 'EVENT' | 'ENTITY';
  objectId: number;
  attributeId: number;
  hierarchyLevelId?: number;
  businessName: string;
  physicalCode: string;
  parentValueId?: number;
  sortOrder: number;
  sourceType: 'MANUAL' | 'PHYSICAL_SYNC' | 'API_SYNC';
  sourceKey?: string;
  lastSyncedAt?: string;
  status: 'ACTIVE' | 'INACTIVE';
}

export type RelationObjectType = 'EVENT' | 'ENTITY';
export type SemanticRelationType = 'EVENT_ENTITY' | 'ENTITY_ENTITY' | 'EVENT_EVENT';
export type RelationCardinality = 'ONE_TO_ONE' | 'ONE_TO_MANY' | 'MANY_TO_ONE' | 'MANY_TO_MANY';
export type RelationDirection = 'FORWARD' | 'REVERSE' | 'BIDIRECTIONAL';

export interface SemanticRelation {
  id: number;
  relationCode: string;
  relationName: string;
  relationType: SemanticRelationType;
  sourceType: RelationObjectType;
  sourceId: number;
  targetType: RelationObjectType;
  targetId: number;
  relationRole?: string;
  sourceAttributeId?: number;
  targetAttributeId?: number;
  cardinality: RelationCardinality;
  direction: RelationDirection;
  priority: number;
  joinType: 'INNER' | 'LEFT';
  required: boolean;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface SchemaMapping {
  id: number;
  objectType: RelationObjectType;
  objectId: number;
  datasourceName: string;
  schemaName: string;
  tableName: string;
  tableAlias?: string;
}

export interface FieldMapping {
  id: number;
  objectType: RelationObjectType;
  objectId: number;
  attributeId: number;
  physicalFieldName: string;
  physicalDataType: string;
  fieldRole: 'PRIMARY_KEY' | 'JOIN_KEY' | 'DIMENSION' | 'MEASURE' | 'TIME' | 'TEXT';
  sqlTransform?: string;
}

export type MetricType = 'BASIC' | 'COMPOSITE';
export type MetricStatus = 'DRAFT' | 'PUBLISHED' | 'INACTIVE';

export type CaliberOperator =
  | '=' | '!=' | '>' | '>=' | '<' | '<='
  | 'IN' | 'NOT_IN' | 'BETWEEN' | 'LIKE' | 'IS_NULL' | 'NOT_NULL';

export interface CaliberCondition {
  attributeId: number;
  attributeCode: string;
  attributeName?: string;
  op: CaliberOperator;
  values: string[];
}

export interface CaliberFilter {
  logic: 'AND' | 'OR';
  conditions: CaliberCondition[];
}

export type FormulaTokenType = 'METRIC' | 'OP' | 'NUM' | 'LPAREN' | 'RPAREN';

export interface FormulaToken {
  type: FormulaTokenType;
  value: string;
  metricId?: number;
  metricCode?: string;
}

export interface SemanticMetric {
  id: number;
  metricCode: string;
  metricName: string;
  metricType: MetricType;
  description?: string;
  unit?: string;
  owner?: string;
  version: number;
  status: MetricStatus;
  publishedAt?: string;
  eventId?: number;
  eventCode: string;
  eventName: string;
  baseAttributeId?: number;
  baseAttributeCode?: string;
  defaultOperator?: string;
  caliberFilter?: CaliberFilter;
  formula?: string;
  formulaTokens?: FormulaToken[];
  editability?: 'EDITABLE' | 'READ_ONLY';
  compatibilityReason?: string;
  ruleIds: number[];
}

export interface TermAlias {
  id: number;
  aliasText: string;
  targetType: TargetType;
  targetId: number;
  targetCode: string;
  targetName: string;
  priority: number;
  source: AliasSource;
  isConfirmed: boolean;
  conflictStatus: ConflictStatus;
  sourceObjectCode?: string;
}

export interface SemanticTerm {
  id: number;
  termCode: string;
  termName: string;
  businessDefinition: string;
  tags: string[];
  owner: string;
  relatedObjects: TermRelatedObject[];
  usageContext: string;
  notes: string;
  participateInExplanation: boolean;
  status: 'ACTIVE' | 'INACTIVE';
}

export interface TermRelatedObject {
  objectType: TermRelatedObjectType;
  objectId: number;
  objectCode: string;
  objectName: string;
  relationType: 'DEFINES' | 'SYNONYM' | 'RELATED';
}

export interface UnknownTerm {
  id: number;
  termText: string;
  occurrenceCount: number;
  lastOccurredAt: string;
  resolutionStatus: 'OPEN' | 'RESOLVED' | 'IGNORED';
}

export interface ValidationIssue {
  severity: 'BLOCKER' | 'WARNING' | 'INFO';
  checkCode: string;
  message: string;
}

/* ===== 指标目标 ===== */
export type TargetPeriod = 'YEAR' | 'QUARTER' | 'MONTH' | 'WEEK' | 'DAY';
export type TargetValueType = 'ABSOLUTE' | 'GROWTH' | 'RATIO';
export type TargetStatus = 'DRAFT' | 'ACTIVE' | 'INACTIVE';

export interface MetricTarget {
  id: number;
  metricId: number;
  metricCode?: string;
  metricName?: string;
  valueType: TargetValueType;
  period: TargetPeriod;
  targetValue: number;
  dimensionFilter?: CaliberFilter;
  dimensionLabel?: string;
  effectiveStart: string;
  effectiveEnd: string;
  status: TargetStatus;
}

/* ===== 业务规则 ===== */
export type RuleMode = 'COMPARISON' | 'FILTER' | 'EXISTENCE' | 'COMPOSITE';
export type RuleTargetObjectType = 'METRIC' | 'EVENT' | 'ENTITY';
export type RuleStatus = 'DRAFT' | 'PUBLISHED' | 'INACTIVE';

export interface ComparisonExpression {
  metricId?: number;
  metricCode?: string;
  operator: '<' | '<=' | '>' | '>=' | '=' | '!=';
  thresholdSource: 'CONSTANT' | 'METRIC_TARGET' | 'METRIC';
  thresholdValue?: number;
  targetId?: number;
  ratio?: number;
}

export interface FilterExpression {
  entityId?: number;
  logic: 'AND' | 'OR';
  conditions: CaliberCondition[];
}

export interface ExistenceExpression {
  eventId?: number;
  aggregate: 'EXISTS' | 'COUNT';
  operator?: '>' | '>=' | '<' | '<=' | '=';
  value?: number;
  timeRuleCode?: string;
}

export interface CompositeExpression {
  logic: 'AND' | 'OR' | 'NOT';
  ruleIds: number[];
}

export type RuleExpression =
  | ComparisonExpression
  | FilterExpression
  | ExistenceExpression
  | CompositeExpression;

export interface BusinessRule {
  id: number;
  ruleCode: string;
  ruleName: string;
  description?: string;
  mode: RuleMode;
  targetObjectType: RuleTargetObjectType;
  targetObjectId: number;
  targetObjectName?: string;
  expression: RuleExpression;
  triggerWords: string[];
  isNegative: boolean;
  oppositeRuleId?: number;
  status: RuleStatus;
  version: number;
  owner?: string;
  lastValidation?: { blockers: number; warnings: number; issues: ValidationIssue[] };
  publishedAt?: string;
}

export interface RuleLink {
  id: number;
  ownerType: 'EVENT' | 'ENTITY';
  ownerId: number;
  ruleId: number;
}

/* ===== 预览结果 ===== */
export interface MetricPreviewResult {
  value?: number;
  dependencies: { metricCode: string; metricName: string }[];
  sql: string;
}

export interface RulePreviewResult {
  verdict: 'PASS' | 'FAIL' | 'UNKNOWN';
  actual?: number;
  threshold?: number;
  matchedObjectCount: number;
  logicForm: string;
  sql: string;
}
