package com.linguan.codemd.stage02;

/** Stable Stage 02 failure codes safe for callers and adapters. */
public enum Stage02FailureCode {
    STAGE02_REQUEST_SCHEMA_INVALID,
    STAGE01_RESULT_REPLAY_MISMATCH,
    STAGE01_GRAPH_NOT_FLOW_READY,
    FLOW_PROFILE_REFERENCE_INVALID,
    EVIDENCE_PROFILE_REFERENCE_INVALID,
    FLOW_GRAPH_REFERENCE_BROKEN,
    FLOW_BRANCH_POLARITY_MISSING,
    FLOW_OUTCOME_CLOSURE_BROKEN,
    FLOW_FACT_PROOF_REFERENCE_BROKEN,
    FLOW_ACCOUNTING_INVARIANT_BROKEN,
    EVIDENCE_SOURCE_REOPEN_MISMATCH,
    EVIDENCE_PROJECTION_UNSATISFIABLE,
    EVIDENCE_PROJECTION_INVARIANT_BROKEN,
    STAGE02_RESOURCE_LIMIT_EXCEEDED,
    STAGE02_IDENTITY_COLLISION
}
