package com.linguan.codemd.stage03;

/** Stable failure categories for fail-closed controlled generation. */
public enum Stage03FailureCode {
    STAGE03_REQUEST_INVALID,
    STAGE03_REPLAY_INPUT_INVALID,
    STAGE03_REPLAY_ROUND_SET_INVALID,
    STAGE03_REPLAY_TASK_MISMATCH,
    STAGE03_REPLAY_RESPONSE_DIGEST_MISMATCH,
    STAGE02_RESULT_REPLAY_MISMATCH,
    REGISTRY_INVALID,
    TECHNICAL_FALLBACK_NOT_TOTAL,
    CAPSULE_CLOSURE_BROKEN,
    MODEL_RUNTIME_IDENTITY_MISMATCH,
    MODEL_RESPONSE_INVALID,
    MODEL_RESPONSE_IDENTITY_MISMATCH,
    MODEL_RESPONSE_REFERENCE_INVALID,
    MODEL_REVIEW_NOT_CLOSED,
    RESOURCE_LIMIT_EXCEEDED,
    READER_INVARIANT_BROKEN
}
