import { useState, useMemo } from 'react';
import { Button, Drawer, Dropdown, Form, Input, Select, InputNumber, Switch, Tag, Space, Card, Descriptions, Modal, message, Segmented, Alert } from 'antd';
import { PlusOutlined, EditOutlined, MoreOutlined } from '@ant-design/icons';
import { useStore } from '../../store/useStore';
import { getPreviewText } from '../../utils/timeCalculator';
import type { TimeRule, Granularity, RangeType } from '../../types';
import ResponsiveDataView, { ResponsiveDataCard } from '../../components/ResponsiveDataView';

const granOptions: { value: Granularity; label: string }[] = [
  { value: 'YEAR', label: '年' }, { value: 'QUARTER', label: '季度' }, { value: 'MONTH', label: '月' }, { value: 'WEEK', label: '周' }, { value: 'DAY', label: '日' },
];
const rangeTypeLabels: Record<RangeType, string> = {
  CURRENT: '当前周期', PREVIOUS: '上一周期', ROLLING: '滚动窗口',
  SINCE_START: '起始至今', HOLIDAY: '节假日', CUSTOM: '自定义口径', ABSOLUTE: '绝对时间',
};
const rangeTypeColors: Record<RangeType, string> = {
  CURRENT: 'blue', PREVIOUS: 'geekblue', ROLLING: 'purple',
  SINCE_START: 'cyan', HOLIDAY: 'red', CUSTOM: 'orange', ABSOLUTE: 'default',
};
const granLabels: Record<string, string> = { YEAR: '年', QUARTER: '季度', MONTH: '月', WEEK: '周', DAY: '日' };

export default function RuleTab({ readOnly = false }: { readOnly?: boolean }) {
  const { rules, calendars, holidayCalendars, addRule, updateRule, deleteRule, toggleRuleStatus } = useStore();
  const [view, setView] = useState<string>('custom');
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<TimeRule | null>(null);
  const [previewId, setPreviewId] = useState<number | null>(null);
  const [form] = Form.useForm();

  const autoRules = rules.filter((r) => r.isAutoGenerated);
  const customRules = rules.filter((r) => !r.isAutoGenerated);

  const rangeType = Form.useWatch('rangeType', form);

  const autoRulesByCalendar = useMemo(() => {
    const grouped: Record<string, TimeRule[]> = {};
    for (const r of autoRules) {
      if (!grouped[r.calendarCode]) grouped[r.calendarCode] = [];
      grouped[r.calendarCode].push(r);
    }
    return grouped;
  }, [autoRules]);

  const handleNew = () => {
    setEditing(null);
    form.resetFields();
    form.setFieldsValue({ rangeType: 'CURRENT', calendarCode: 'natural', granularity: 'YEAR', offsetValue: 0, offsetStart: 0, offsetEnd: 0, priority: 0, participateInReasoning: true, isRecurring: false });
    setOpen(true);
  };
  const handleEdit = (r: TimeRule) => { setEditing(r); form.setFieldsValue(r); setOpen(true); };
  const handleDelete = (id: number) => { deleteRule(id); message.success('删除成功'); };
  const getOffsetOrDays = (rule: TimeRule) => {
    if (rule.rangeType === 'ROLLING') return `${rule.rollingDays || rule.paramPattern || '—'}天`;
    if (rule.rangeType === 'SINCE_START') return '—';
    return rule.offsetValue ?? '—';
  };
  const renderCustomRuleActions = (rule: TimeRule) => readOnly ? <span style={{ color: '#8c8c8c' }}>只读</span> : (
    <Space size={0}>
      <Button size="small" icon={<EditOutlined />} onClick={() => handleEdit(rule)}>编辑</Button>
      <Dropdown
        trigger={['click']}
        menu={{
          items: [{ key: 'preview', label: '预览' }, { type: 'divider' }, { key: 'delete', label: '删除', danger: true }],
          onClick: ({ key }) => {
            if (key === 'preview') setPreviewId(rule.id);
            if (key === 'delete') Modal.confirm({
              title: `删除时间规则“${rule.ruleText}”？`,
              okText: '删除',
              okButtonProps: { danger: true },
              cancelText: '取消',
              onOk: () => handleDelete(rule.id),
            });
          },
        }}
      >
        <Button type="text" size="small" icon={<MoreOutlined />} aria-label={`更多操作：${rule.ruleText}`} />
      </Dropdown>
    </Space>
  );

  const handleSave = () => {
    form.validateFields().then((values) => {
      if (editing) {
        updateRule(editing.id, values);
        message.success('更新成功');
      } else {
        if (rules.find((r) => r.ruleCode === values.ruleCode)) { message.error('规则编码已存在'); return; }
        if (rules.find((r) => r.ruleText === values.ruleText)) { message.error('时间表达已存在'); return; }
        addRule({ ...values, isAutoGenerated: false, status: 'ACTIVE' });
        message.success('创建成功');
      }
      setOpen(false);
    });
  };

  const previewRule = previewId !== null ? rules.find((r) => r.id === previewId) : null;
  const previewCal = previewRule ? calendars.find((c) => c.calendarCode === previewRule.calendarCode) : null;
  const previewText = previewRule && previewCal ? getPreviewText(previewRule, previewCal) : null;
  const previewDateLabel = new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium' }).format(new Date());

  const autoColumns = [
    { title: '时间表达', dataIndex: 'ruleText', key: 'text', width: 220, render: (v: string) => <strong>{v}</strong> },
    { title: '编码', dataIndex: 'ruleCode', key: 'code', width: 190, render: (v: string) => <code>{v}</code> },
    { title: '范围类型', dataIndex: 'rangeType', key: 'range', width: 150, render: (v: RangeType) => <Tag color={rangeTypeColors[v]}>{rangeTypeLabels[v]}</Tag> },
    { title: '粒度', dataIndex: 'granularity', key: 'gran', width: 100, render: (v: string) => granLabels[v] || v },
    { title: '偏移/天数', key: 'offset', width: 120, render: (_: unknown, r: TimeRule) => getOffsetOrDays(r) },
    { title: '预览', key: 'preview', width: 300, render: (_: unknown, r: TimeRule) => {
      const cal = calendars.find((c) => c.calendarCode === r.calendarCode);
      return cal ? <span style={{ color: '#666', fontSize: 12 }}>{getPreviewText(r, cal)}</span> : '—';
    }},
    { title: '状态', key: 'status', width: 100, render: (_: unknown, r: TimeRule) => (
      <Switch size="small" disabled={readOnly} checked={r.status === 'ACTIVE'} onChange={() => toggleRuleStatus(r.id)} checkedChildren="启用" unCheckedChildren="禁用" />
    )},
  ];

  const customColumns = [
    { title: '时间表达', dataIndex: 'ruleText', key: 'text', width: 220, render: (v: string) => <strong>{v}</strong> },
    { title: '编码', dataIndex: 'ruleCode', key: 'code', width: 190, render: (v: string) => <code>{v}</code> },
    { title: '范围类型', dataIndex: 'rangeType', key: 'range', width: 150, render: (v: RangeType) => <Tag color={rangeTypeColors[v]}>{rangeTypeLabels[v]}</Tag> },
    { title: '日历', dataIndex: 'calendarCode', key: 'cal', width: 160, render: (v: string) => calendars.find((c) => c.calendarCode === v)?.calendarName || '未绑定日历' },
    { title: '粒度', dataIndex: 'granularity', key: 'gran', width: 100, render: (v: string) => granLabels[v] || v },
    { title: '预览', key: 'preview', width: 300, render: (_: unknown, r: TimeRule) => {
      const cal = calendars.find((c) => c.calendarCode === r.calendarCode);
      return cal ? <span style={{ color: '#666', fontSize: 12 }}>{getPreviewText(r, cal)}</span> : '—';
    }},
    { title: '操作', key: 'action', width: 126, render: (_: unknown, r: TimeRule) => renderCustomRuleActions(r) },
  ];

  return (
    <>
      <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Segmented
          value={view}
          onChange={(v) => setView(v as string)}
          options={[
            { label: `自动生成规则（${autoRules.length} 条）`, value: 'auto' },
            { label: `自定义规则（${customRules.length} 条）`, value: 'custom' },
          ]}
        />
        {view === 'custom' && !readOnly && <Button type="primary" icon={<PlusOutlined />} onClick={handleNew}>新建自定义规则</Button>}
      </div>

      {previewRule && previewText && (
        <Card size="small" style={{ marginBottom: 16, background: '#f6ffed', borderColor: '#b7eb8f' }} title={`预览：${previewRule.ruleText}`}>
          <Descriptions size="small" column={2}>
            <Descriptions.Item label="预览基准日期">{previewDateLabel}</Descriptions.Item>
            <Descriptions.Item label="日历">{previewCal?.calendarName}</Descriptions.Item>
            <Descriptions.Item label="范围类型"><Tag color={rangeTypeColors[previewRule.rangeType]}>{rangeTypeLabels[previewRule.rangeType]}</Tag></Descriptions.Item>
            <Descriptions.Item label="日期范围" span={2}><strong>{previewText}</strong></Descriptions.Item>
            {previewRule.rangeType === 'HOLIDAY' && <Descriptions.Item label="节假日偏移">{previewRule.holidayCode}（偏移 {previewRule.offsetStart ?? 0} ~ {previewRule.offsetEnd ?? 0} 天）</Descriptions.Item>}
            {previewRule.rangeType === 'CUSTOM' && <Descriptions.Item label="固定区间">{previewRule.fixedStartDate} ~ {previewRule.fixedEndDate}{previewRule.isRecurring ? '（每年重复）' : ''}</Descriptions.Item>}
          </Descriptions>
        </Card>
      )}

      {view === 'auto' ? (
        <div>
          <Alert type="info" showIcon message="系统模板规则" description="这些规则由当前日历配置生成，可以启用或停用；资料中明确给出的规则会显示在“资料与自定义规则”中。" style={{ marginBottom: 16 }} />
          {Object.entries(autoRulesByCalendar).map(([calCode, calRules]) => {
            const cal = calendars.find((c) => c.calendarCode === calCode);
            return (
              <Card key={calCode} size="small" title={<span>{cal?.calendarName || calCode} <Tag>{calRules.length} 条</Tag></span>} style={{ marginBottom: 12 }}>
                <ResponsiveDataView
                  ariaLabel={`${cal?.calendarName || calCode}自动时间规则列表`}
                  dataSource={calRules}
                  columns={autoColumns}
                  rowKey="id"
                  minTableWidth={1180}
                  pagination={{ pageSize: 20, showSizeChanger: false }}
                  tableProps={{ size: 'small' }}
                  renderCard={(rule) => {
                    const calendar = calendars.find((item) => item.calendarCode === rule.calendarCode);
                    return <ResponsiveDataCard
                      title={rule.ruleText}
                      subtitle={<code>{rule.ruleCode}</code>}
                      status={<Switch size="small" disabled={readOnly} checked={rule.status === 'ACTIVE'} onChange={() => toggleRuleStatus(rule.id)} checkedChildren="启用" unCheckedChildren="禁用" />}
                      fields={[
                        { label: '范围类型', value: rangeTypeLabels[rule.rangeType] },
                        { label: '粒度', value: granLabels[rule.granularity] || rule.granularity },
                        { label: '偏移/天数', value: getOffsetOrDays(rule) },
                        { label: '预览', value: calendar ? getPreviewText(rule, calendar) : '—', wide: true },
                      ]}
                    />;
                  }}
                />
              </Card>
            );
          })}
        </div>
      ) : (
        <ResponsiveDataView
          ariaLabel="时间规则列表"
          dataSource={customRules}
          columns={customColumns}
          rowKey="id"
          minTableWidth={1250}
          pagination={{ pageSize: 20, showSizeChanger: false }}
          tableProps={{ size: 'small' }}
          renderCard={(rule) => {
            const calendar = calendars.find((item) => item.calendarCode === rule.calendarCode);
            return <ResponsiveDataCard
              title={rule.ruleText}
              subtitle={<code>{rule.ruleCode}</code>}
              status={<Tag color={rule.status === 'ACTIVE' ? 'green' : 'default'}>{rule.status === 'ACTIVE' ? '启用' : '禁用'}</Tag>}
              fields={[
                { label: '范围类型', value: rangeTypeLabels[rule.rangeType] },
                { label: '日历', value: calendar?.calendarName || '未绑定日历' },
                { label: '粒度', value: granLabels[rule.granularity] || rule.granularity },
                { label: '预览', value: calendar ? getPreviewText(rule, calendar) : '—', wide: true },
              ]}
              actions={renderCustomRuleActions(rule)}
            />;
          }}
        />
      )}

      <Drawer title={editing ? '编辑自定义规则' : '新建自定义规则'} width="min(560px, 100vw)" open={open} onClose={() => setOpen(false)}
        footer={<Space style={{ width: '100%', justifyContent: 'flex-end' }}><Button onClick={() => setOpen(false)}>取消</Button><Button type="primary" onClick={handleSave}>保存</Button></Space>}>
        <Form form={form} layout="vertical">
          <Form.Item name="ruleText" label="时间表达" rules={[{ required: true }]} extra="用户看到的词，如「大促期间」「春节期间」">
            <Input placeholder="如：大促期间、春节期间" />
          </Form.Item>
          <Form.Item name="ruleCode" label="规则编码" rules={[{ required: true }]} extra="空间内唯一，建议英文">
            <Input placeholder="如：promo_period" disabled={!!editing} />
          </Form.Item>
          <Form.Item name="calendarCode" label="使用日历" rules={[{ required: true }]}>
            <Select options={calendars.map((c) => ({ value: c.calendarCode, label: c.calendarName }))} />
          </Form.Item>
          <Form.Item name="rangeType" label="范围类型" rules={[{ required: true }]}>
            <Select options={[
              { value: 'CURRENT', label: '当前周期 — 今年/本月/本季度' },
              { value: 'PREVIOUS', label: '上一周期 — 去年/上月/上季度' },
              { value: 'ROLLING', label: '滚动窗口 — 近7天/近30天/近N天' },
              { value: 'SINCE_START', label: '起始至今 — 年初至今/月初至今' },
              { value: 'HOLIDAY', label: '节假日 — 春节/国庆/双十一' },
              { value: 'CUSTOM', label: '自定义口径 — 固定日期区间' },
            ]} />
          </Form.Item>

          {(rangeType === 'CURRENT' || rangeType === 'PREVIOUS') && (
            <>
              <Form.Item name="granularity" label="时间粒度" rules={[{ required: true }]}>
                <Select options={granOptions} />
              </Form.Item>
              <Form.Item name="offsetValue" label="偏移量" extra="当前=0，上一=-1，前年=-2">
                <InputNumber style={{ width: '100%' }} />
              </Form.Item>
            </>
          )}

          {rangeType === 'ROLLING' && (
            <>
              <Form.Item name="rollingDays" label="滚动天数" rules={[{ required: true }]}>
                <InputNumber min={1} style={{ width: '100%' }} placeholder="如：7、30、90" />
              </Form.Item>
              <Form.Item name="paramPattern" label="参数名称（可选）" extra="填写后用户可在问数时指定天数，如「近N天」">
                <Input placeholder="如：N" />
              </Form.Item>
              <Form.Item name="paramDefault" label="参数默认值" extra="用户不指定时的默认天数">
                <InputNumber min={1} style={{ width: '100%' }} />
              </Form.Item>
            </>
          )}

          {rangeType === 'SINCE_START' && (
            <Form.Item name="granularity" label="时间粒度" rules={[{ required: true }]}>
              <Select options={granOptions.filter((o) => ['YEAR', 'QUARTER', 'MONTH'].includes(o.value))} />
            </Form.Item>
          )}

          {rangeType === 'HOLIDAY' && (
            <>
              <Form.Item name="holidayCode" label="关联节假日" rules={[{ required: true }]}>
                <Select options={holidayCalendars.map((h) => ({ value: h.holidayCode, label: `${h.holidayName}（${h.holidayCode}）` }))} placeholder="选择节假日" />
              </Form.Item>
              <Alert type="info" showIcon style={{ marginBottom: 16 }}
                message="通过偏移天数精确定义相对节假日的时间区间"
                description={
                  <div style={{ fontSize: 12, lineHeight: 2 }}>
                    <div><strong>春节期间</strong>：起始=0，结束=0 → 节假日完整区间</div>
                    <div><strong>春节前一周</strong>：起始=-7，结束=-1 → 节假日前7天到前1天</div>
                    <div><strong>国庆后三天</strong>：起始=1，结束=3 → 节假日后1天到后3天</div>
                    <div><strong>双十一预热期</strong>：起始=-15，结束=-1 → 节假日前15天到前1天</div>
                  </div>
                }
              />
              <Form.Item name="offsetStart" label="偏移起始天数" extra="相对节假日开始日的偏移，负数=节前，0=节当天">
                <InputNumber style={{ width: '100%' }} placeholder="如：0（节当天）或 -7（节前7天）" />
              </Form.Item>
              <Form.Item name="offsetEnd" label="偏移结束天数" extra="相对节假日结束日的偏移，0=节最后一天，正数=节后">
                <InputNumber style={{ width: '100%' }} placeholder="如：0（节最后一天）或 3（节后3天）" />
              </Form.Item>
            </>
          )}

          {rangeType === 'CUSTOM' && (
            <>
              <Form.Item name="fixedStartDate" label="固定开始日期" rules={[{ required: true }]} extra="格式：MM-DD（每年重复）或 YYYY-MM-DD（一次性）">
                <Input placeholder="如：11-01 或 2026-11-01" />
              </Form.Item>
              <Form.Item name="fixedEndDate" label="固定结束日期" rules={[{ required: true }]} extra="格式同上">
                <Input placeholder="如：11-11 或 2026-11-11" />
              </Form.Item>
              <Form.Item name="isRecurring" label="每年重复" valuePropName="checked" extra="开启后每年自动适用，无需每年修改日期">
                <Switch />
              </Form.Item>
            </>
          )}

          <Form.Item name="priority" label="优先级" extra="数值越小优先级越高">
            <InputNumber style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item name="participateInReasoning" label="参与问数识别" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Drawer>
    </>
  );
}
